package configs

const (
	// PrivateKey ...
	PrivateKey string = "certs/domain.key"
	// Certification  ...
	Certification string = "certs/domain.crt"
	// Host ...
	Host string = "localhost"
	// Port ...
	Port uint = 10443
)
